filebeat.inputs:
  - type: log
    id: snort-alerts
    enabled: true
    paths:
      - /var/log/snort/alert.fast
    fields:
      log_type: snort
    fields_under_root: true

  - type: log
    id: firewall-drops
    enabled: true
    paths:
      - /var/log/firewall/firewall.log
    fields:
      log_type: firewall
    fields_under_root: true

  - type: log
    id: nginx-logs
    enabled: true
    paths:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
    fields:
      log_type: nginx
    fields_under_root: true

processors:
  - add_host_metadata: {}
  - add_cloud_metadata: {}
  - add_docker_metadata: {}

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "snort-%{+yyyy.MM.dd}"
      when.equals:
        log_type: "snort"
    - index: "firewall-%{+yyyy.MM.dd}"
      when.equals:
        log_type: "firewall"
    - index: "nginx-%{+yyyy.MM.dd}"
      when.equals:
        log_type: "nginx"

logging.level: info
logging.to_files: false

strict.perms: false
